/*
 *   Copyright (c) 2023 Duart Snel
 *   All rights reserved.

 *   Licensed under the Apache License, Version 2.0 (the "License");
 *   you may not use this file except in compliance with the License.
 *   You may obtain a copy of the License at

 *   http://www.apache.org/licenses/LICENSE-2.0

 *   Unless required by applicable law or agreed to in writing, software
 *   distributed under the License is distributed on an "AS IS" BASIS,
 *   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *   See the License for the specific language governing permissions and
 *   limitations under the License.
 */

import { useRef, useState } from "react";
import {
  Container,
  Row,
  Col,
  ListGroup,
  Image,
  Stack,
  Form,
  Badge,
} from "react-bootstrap";
import RegularCard from "../components/Cards/RegularCard";
import { useToolBar } from "../components/Hooks/useToolBar";
import { InlineCard } from "../components/Modals/InlineCard";
import { downloadPlainText } from "../components/utils/download";
import { ToolBarItemType } from "../context/ToolBarContext";

export default function ExportView() {
  const printRef = useRef<HTMLDivElement | null>(null);
  const [showExportOptions, setShowExportOptions] = useState(false);
  const [printSettings, setPrintSettings] = useState({
    background: "#1e1e1e",
    transitiveIncluded: true,
    showCustomNotes: false,
  });
  const [customNotes, setCustomNotes] = useState("Nothing provided.");
  // TODO: take in scan ID as url parameter.. go from there.
  // TODO: show box with 'issues' or 'notes' if applicable, add ability to turn this off in export settings
  // TODO: find a way to show when a dependencies license has been manually resolves (maybe in notice box or something)
  // TODO: add chart display with associated options
  // TODO: table of contents generation
  // TODO: ability to include license text from all the modules in the export!

  useToolBar([
    {
      type: ToolBarItemType.BUTTON,
      title: "Export options",
      icon: "bi bi-sliders",
      onClick: () => {
        setShowExportOptions(true);
      },
    },
    {
      type: ToolBarItemType.SEPARATOR,
    },
    {
      type: ToolBarItemType.BUTTON,
      title: "Download PDF",
      icon: "bi bi-filetype-pdf",
      onClick: () => {
        print();
      },
    },
    {
      type: ToolBarItemType.BUTTON,
      title: "HTML",
      icon: "bi bi-filetype-html",
      onClick: () => {
        // TODO: change file name to something more meaningful
        downloadPlainText("export.html", constructHTML());
      },
    },
    {
      type: ToolBarItemType.BUTTON,
      title: "CSV",
      icon: "bi bi-filetype-csv",
      onClick: () => {
        // TODO: implement csv export when data structure is available
      },
    },
    {
      type: ToolBarItemType.BUTTON,
      title: "Text",
      icon: "bi bi-file-earmark-text",
      onClick: () => {
        // TODO: implement txt export when data structure is available
      },
    },
  ]);

  const constructHTML = () => {
    return `<html>
    <head>
        <title>PDF export</title>
        ${[
          ...document.querySelectorAll('link[rel="stylesheet"], style'),
        ].reduce((acc, node) => (acc += node.outerHTML), "")}
        <style>
            @page {
                size: A4;
                margin: 0 !important;
                padding: 0 !important;;
                border: none !important;
                background: ${printSettings.background};
            }
        </style>
    </head>
    <body onafterprint="self.close()" style="overflow: auto;">
        ${printRef.current!.outerHTML}
    </body>
</html>`;
  };

  const print = () => {
    const printWindow = window.open(
      "",
      "mywindow",
      "status=1,toolbar=0,scrollbars=0,left=0,top=0,innerWidth=793.7008,innerHeight=1122.5197"
    )!;
    printWindow.document.write(constructHTML());

    setTimeout(() => {
      printWindow.document.close();
      printWindow.focus();
      printWindow.print();
      printWindow.close();
    }, 500);
  };

  return (
    <div>
      <h1>Export view</h1>
      <small className="text-muted">
        Please note that the export view only serves as a rough visual
        indication as to how visual exports will end up. Non-visual exports like
        CSV will not carry over the visual aspects of the view.
      </small>
      <hr />
      <div
        ref={printRef}
        style={{
          backgroundColor: printSettings.background,
        }}
      >
        <Container fluid className="py-3">
          <Row className="g-3">
            <Col xs={6}>
              <Image src="http://localhost:3001/logo192.png" />
            </Col>
            <Col xs={6} className="text-end">
              <Stack gap={1}>
                <h6 className="display-4">ReactJS</h6>
                <h6>Version: 1.0.0</h6>
                <h6>Generated by: xxxxxxx</h6>
                <h6>Generated on: 2023-03-09T11:22:48.776Z</h6>
              </Stack>
            </Col>
            {printSettings.showCustomNotes && (
              <Col xs={12}>
              <RegularCard
                title="Custom notes"
                minHeight="100px"
                maxHeight="100%"
              >
                <textarea
                  defaultValue={customNotes}
                  className="w-100 bg-transparent border-0 rounded txt-white"
                  onBlur={(e) => setCustomNotes(e.target.value)}
                >
                </textarea>
              </RegularCard>
            </Col>
            )}
            
            <Col xs={6}>
              <RegularCard title="Status" minHeight="100px">
                <h4 className="txt-green">Compliant</h4>
              </RegularCard>
            </Col>
            <Col xs={6}>
              <RegularCard title="License" minHeight="100px">
                <a
                  href="#test-anchor"
                  className="h4 txt-green text-decoration-none"
                >
                  MIT
                </a>
              </RegularCard>
            </Col>
            <Col xs={12}>
              <RegularCard title="Top-level Dependencies" maxHeight="100%">
                <ListGroup>
                  {Array.from({ length: 100 }).map((_, idx) => (
                    <ListGroup.Item as={"a"} href={`#dep-${idx}`} key={idx}>
                      <Row>
                        <Col xs={6}>Dependency {idx}</Col>
                        <Col xs={2}>
                          <div>1.0.0</div>
                        </Col>
                        <Col xs={2}>
                          <Badge className="bg-grey txt-dark-1">MIT</Badge>
                        </Col>
                        <Col xs={2} className="d-flex justify-content-end">
                          <Badge className="bg-green txt-dark-1">
                            Compliant
                          </Badge>
                        </Col>
                      </Row>
                    </ListGroup.Item>
                  ))}
                </ListGroup>
                <br />
                <br />
                <br />
              </RegularCard>
            </Col>
            {printSettings.transitiveIncluded &&
              Array.from({ length: 100 }).map((_, idx) => (
                <Col xs={16}>
                  <RegularCard
                    title={`Dependency ${idx}'s dependencies`}
                    maxHeight="100%"
                    id={`dep-${idx}`}
                  >
                    <ListGroup>
                      {Array.from({ length: 10 }).map((_, idx) => (
                        <ListGroup.Item key={idx}>
                          Transitive dependency {idx}
                        </ListGroup.Item>
                      ))}
                    </ListGroup>
                    <br />
                    <br />
                    <br />
                  </RegularCard>
                </Col>
              ))}
          </Row>
        </Container>
      </div>
      <InlineCard
        title="Export options"
        show={showExportOptions}
        handleClose={() => setShowExportOptions(false)}
      >
        <Stack gap={2}>
          <div className="d-flex justify-content-between">
            Background color
            <Form.Control
              type="color"
              id="bgColor"
              defaultValue="#1e1e1e"
              title="Choose your color"
              onChange={(e) => {
                setPrintSettings({
                  ...printSettings,
                  background: e.target.value,
                });
              }}
            />
          </div>

          <div className="d-flex justify-content-between">
            Include transitive dependencies
            <Form.Check
              onChange={(e) => {
                setPrintSettings({
                  ...printSettings,
                  transitiveIncluded: e.target.checked,
                });
              }}
              type={"checkbox"}
              defaultChecked={printSettings.transitiveIncluded}
            />
          </div>

          <div className="d-flex justify-content-between">
            Add custom notes box
            <Form.Check
              onChange={(e) => {
                setPrintSettings({
                  ...printSettings,
                  showCustomNotes: e.target.checked,
                });
              }}
              type={"checkbox"}
              defaultChecked={printSettings.showCustomNotes}
            />
          </div>
        </Stack>
      </InlineCard>
    </div>
  );
}
